# Generated by Django 5.2.6 on 2025-09-25 06:42

from django.db import migrations
from django.contrib.auth.models import User


def create_test_users(apps, schema_editor):
    """Создает тестовых пользователей для Playwright тестов"""
    users_data = [
        {'username': 'test_user', 'password': 'testpass123', 'first_name': 'Test', 'last_name': 'User'},
        {'username': 'another_user', 'password': 'testpass123', 'first_name': 'Another', 'last_name': 'User'},
        {'username': 'third_user', 'password': 'testpass123', 'first_name': 'Third', 'last_name': 'User'},
    ]

    for user_data in users_data:
        if not User.objects.filter(username=user_data['username']).exists():
            User.objects.create_user(**user_data)


def reverse_create_test_users(apps, schema_editor):
    """Удаляет тестовых пользователей"""
    User.objects.filter(username__in=['test_user', 'another_user', 'third_user']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_test_users, reverse_create_test_users),
    ]
